%% @author Couchbase <info@couchbase.com>
%% @copyright 2016-Present Couchbase, Inc.
%%
%% Use of this software is governed by the Business Source License included in
%% the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
%% file, in accordance with the Business Source License, use of this software
%% will be governed by the Apache License, Version 2.0, included in the file
%% licenses/APL2.txt.
%%
%% @doc rbac roles for older releases kept for backward compatibility

-module(menelaus_old_roles).

-include("rbac.hrl").
-include("ns_common.hrl").

-export([roles_pre_76/0,
         roles_pre_79/0,
         roles_pre_totoro/0,
         pre_totoro_ui_roles/0]).

-spec roles_pre_76() -> [rbac_role_def(), ...].
roles_pre_76() ->
    [{admin, [],
      [{name, <<"Full Admin">>},
       {folder, admin},
       {desc, <<"Can manage all cluster features (including security). "
                "This user can access the web console. This user can read and "
                "write all data.">>},
       {ce, true}],
      [{[], all}]},
     {ro_admin, [],
      [{name, <<"Read-Only Admin">>},
       {folder, admin},
       {desc, <<"Can view all cluster statistics. This user can access the "
                "web console.">>},
       {ce, true}],
      [{[{bucket, any}, data], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[admin, security], [read]},
       {[admin, stats_export], [read]},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[], [read, list]}]},
     {security_admin_local, [],
      [{name, <<"Local User Security Admin">>},
       {folder, admin},
       {desc, <<"Can view all cluster statistics and manage local user "
                "roles, but not grant Full Admin or Security Admin roles to "
                "other users or alter their own role. This user can access "
                "the web console. This user cannot read data.">>}],
      [{[admin, security, admin], none},
       {[admin, security, external], none},
       {[admin, security], all},
       {[admin, logs], none},
       {[admin, settings, metrics], none},
       {[{bucket, any}, data], none},
       {[{bucket, any}, views], none},
       {[{bucket, any}, n1ql], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[{bucket, any}], [read]},
       {[analytics], none},
       {[backup], none},
       {[eventing], none},
       {[xdcr], none},
       {[settings, fts], none},
       {[settings, metrics], none},
       {[], [read, list]}]},
     {security_admin_external, [],
      [{name, <<"External User Security Admin">>},
       {folder, admin},
       {desc, <<"Can view all cluster statistics and manage external user "
                "roles, but not grant Full Admin or Security Admin roles to "
                "other users or alter their own role. This user can access "
                "the web console. This user cannot read data.">>}],
      [{[admin, security, admin], none},
       {[admin, security, local], none},
       {[admin, security], all},
       {[admin, logs], none},
       {[admin, settings], none},
       {[{bucket, any}, data], none},
       {[{bucket, any}, views], none},
       {[{bucket, any}, n1ql], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[{bucket, any}], [read]},
       {[analytics], none},
       {[backup], none},
       {[eventing], none},
       {[xdcr], none},
       {[settings, fts], none},
       {[], [read, list]}]},
     {cluster_admin, [],
      [{name, <<"Cluster Admin">>},
       {folder, admin},
       {desc, <<"Can manage all cluster features except security. This user "
                "can access the web console. This user cannot read data.">>}],
      [{[admin, internal], none},
       {[admin, security], none},
       {[admin, diag], [read]},
       {[admin, settings, metrics], none},
       {[{bucket, any}, data], none},
       {[{bucket, any}, views], none},
       {[{bucket, any}, n1ql], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[n1ql, curl], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[], all}]},
     {eventing_admin, [],
      [{name, <<"Eventing Full Admin">>},
       {folder, admin},
       {desc, <<"Can create/manage eventing functions. This user can access "
                "the web console">>}],
      [{[admin], none},
       {[xdcr], none},
       {[{bucket, any}, xdcr], none},
       {[{bucket, any}], all},
       {[n1ql], all},
       {[eventing], all},
       {[analytics], all},
       {[buckets], all},
       {[settings, metrics], none},
       {[], [read]}]},
     {backup_admin, [],
      [{name, <<"Backup Full Admin">>},
       {folder, admin},
       {desc, <<"Can perform backup related tasks. This user can access "
                "the web console">>}],
      [{[admin], none},
       {[settings, metrics], none},
       {[], all}]},
     {bucket_admin, [bucket_name],
      [{name, <<"Bucket Admin">>},
       {folder, bucket},
       {desc, <<"Can manage ALL bucket features for a given bucket (including "
                "start/stop XDCR). This user can access the web console. This "
                "user cannot read data.">>}],
      [{[{bucket, bucket_name}, xdcr], [read, execute]},
       {[{bucket, bucket_name}, data], none},
       {[{bucket, bucket_name}, views], none},
       {[{bucket, bucket_name}, n1ql], none},
       {[{bucket, bucket_name}, fts], none},
       {[{bucket, any}, analytics], none},
       {[{bucket, bucket_name}], all},
       {[{bucket, any}, settings], [read]},
       {[{bucket, any}], none},
       {[xdcr], none},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[settings, metrics], none},
       {[], [read]}]},
     {scope_admin, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scopes">>},
       {folder, bucket},
       {desc, <<"Can create/delete scopes and collections within a given bucket. "
                "This user cannot access the web console.">>}],
      [{[{collection, [bucket_name, scope_name, any]}, collections], all}]},
     {bucket_full_access, [bucket_name],
      [{name, <<"Application Access">>},
       {folder, bucket},
       {desc, <<"Full access to bucket data. This user cannot access the web "
                "console and is intended only for application access. This "
                "user can read and write data.">>},
       {ce, true}],
      [{[{bucket, bucket_name}, data], all},
       {[{bucket, bucket_name}, views], all},
       {[{bucket, bucket_name}, n1ql, index], all},
       {[{bucket, bucket_name}, n1ql], [execute]},
       {[{bucket, bucket_name}], [read, flush]},
       {[{bucket, bucket_name}, settings], [read]},
       {[pools], [read]}]},
     {views_admin, [bucket_name],
      [{name, <<"Views Admin">>},
       {folder, admin},
       {desc, <<"Can create and manage views of a given bucket. This user can "
                "access the web console. This user can read some data.">>}],
      [{[{bucket, bucket_name}, views], all},
       {[{bucket, bucket_name}, data], [read]},
       {[{bucket, bucket_name}, stats], [read]},
       {[{bucket, any}, settings], [read]},
       {[{bucket, any}], none},
       {[{bucket, bucket_name}, n1ql], [execute]},
       {[xdcr], none},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[settings, metrics], none},
       {[], [read]}]},
     {views_reader, [bucket_name],
      [{name, <<"Views Reader">>},
       {folder, views},
       {desc, <<"Can read data from the views of a given bucket. This user "
                "cannot access the web console and is intended only for "
                "application access. This user can read some data.">>}],
      [{[{bucket, bucket_name}, views], [read]},
       {[{bucket, bucket_name}, data, docs], [read]},
       {[pools], [read]}]},
     {replication_admin, [],
      [{name, <<"XDCR Admin">>},
       {folder, xdcr},
       {desc, <<"Can administer XDCR features to create cluster references and "
                "replication streams out of this cluster. This user can "
                "access the web console. This user can read some data.">>}],
      [{[{bucket, any}, xdcr], all},
       {[{bucket, any}, data], [read]},
       {[{bucket, any}, settings], [read]},
       {[{bucket, any}, stats], [read]},
       {[{bucket, any}, collections], [read]},
       {[{bucket, any}], none},
       {[xdcr, developer], [read]},
       {[xdcr], all},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[settings, metrics], none},
       {[], [read]}]},
     {data_reader, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data Reader">>},
       {folder, data},
       {desc, <<"Can read data from a given bucket, scope or collection. "
                "This user cannot access the web console and is intended only "
                "for application access. This user can read data, but cannot "
                "write it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[pools], [read]}]},
     {data_writer, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data Writer">>},
       {folder, data},
       {desc, <<"Can write data to a given bucket, scope or collection. "
                "This user cannot access the web console and is intended only "
                "for application access. This user can write data, but cannot "
                "read it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs],
        [insert, upsert, delete]},
       {[{bucket, bucket_name}, settings], [read]},
       {[pools], [read]}]},
     {data_dcp_reader, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data DCP Reader">>},
       {folder, data},
       {desc, <<"Can initiate DCP streams for a given bucket, scope or "
                "collection. This user cannot access the web console and is "
                "intended only for application access. "
                "This user can read data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, dcpstream], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, sxattr], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, collections], [read]},
       {[{bucket, bucket_name}, data, dcp], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[admin, memcached, idle], [write]},
       {[pools], [read]}]},
     {data_backup, [bucket_name],
      [{name, <<"Data Backup & Restore">>},
       {folder, backup},
       {desc, <<"Can backup and restore a given bucket’s data. This user "
                "cannot access the web console and is intended only for "
                "application access. This user can read data.">>}],
      [{[{collection, [bucket_name, any, any]}, collections], all},
       {[{bucket, bucket_name}, data], all},
       {[{bucket, bucket_name}, views], [read, write]},
       {[{bucket, bucket_name}, fts], [read, write, manage]},
       {[{bucket, bucket_name}, stats], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[{bucket, bucket_name}, n1ql, index], [create, list, build]},
       {[{bucket, bucket_name}, n1ql, meta], [backup]},
       {[{bucket, bucket_name}, analytics], [manage, select]},
       {[analytics], [select, backup]},
       {[pools], [read]}]},
     {data_monitoring, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data Monitor">>},
       {folder, data},
       {desc, <<"Can read statistics for a given bucket, scope or collection. "
                "This user cannot access the web console and is intended only "
                "for application access. This user cannot read data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, stats], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, collections], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[tasks], [read]},
       {[pools], [read]}]},
     {fts_admin, [bucket_name],
      [{name, <<"Search Admin">>},
       {folder, search},
       {desc, <<"Can administer all Full Text Search features. This user can "
                "access the web console. This user can read some data.">>}],
      [{[{bucket, bucket_name}, fts], [read, write, manage]},
       {[{bucket, bucket_name}, collections], [read]},
       {[{bucket, bucket_name}, data, docs], [read]},
       {[settings, fts], [read, write, manage]},
       {[ui], [read]},
       {[pools], [read]},
       {[{bucket, bucket_name}, settings], [read]}]},
     {fts_searcher, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Search Reader">>},
       {folder, search},
       {desc, <<"Can query Full Text Search indexes for a given bucket, scope "
                "or collection. This user can access the web console. This "
                "user can read some data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, fts], [read]},
       {[settings, fts], [read]},
       {[ui], [read]},
       {[pools], [read]},
       {[{bucket, bucket_name}, settings], [read]}]},
     {query_select, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Select">>},
       {folder, 'query'},
       {desc, <<"Can execute a SELECT statement on a given bucket, scope or "
                "collection to retrieve data. This user can access the web "
                "console and can read data, but not write it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, select], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_update, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Update">>},
       {folder, 'query'},
       {desc, <<"Can execute an UPDATE statement on a given bucket, scope or "
                "collection to update data. This user can access the web "
                "console and write data, but cannot read it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, update], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [upsert]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_insert, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Insert">>},
       {folder, 'query'},
       {desc, <<"Can execute an INSERT statement on a given bucket, scope or "
                "collection to add data. This user can access the web console "
                "and insert data, but cannot read it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, insert], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [insert]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_delete, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Delete">>},
       {folder, 'query'},
       {desc, <<"Can execute a DELETE statement on a given bucket, scope or "
                "collection to delete data. This user can access the web "
                "console, but cannot read data. This user can delete data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, delete], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [delete]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_manage_index, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Manage Index">>},
       {folder, 'query'},
       {desc, <<"Can manage indexes for a given bucket, scope or collection. "
                "This user can access the web console, can read statistics "
                "for a given bucket, scope or collection. This user cannot "
                "read data.">>
       }],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, index], all},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, collections], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[{bucket, bucket_name}, stats], [read]},
       {[settings, indexes], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_system_catalog, [],
      [{name, <<"Query System Catalog">>},
       {folder, 'query'},
       {desc, <<"Can look up system catalog information via N1QL. This user "
                "can access the web console, but cannot read user data.">>}],
      [{[{bucket, any}, n1ql, index], [list]},
       {[{bucket, any}, settings], [read]},
       {[n1ql, meta], [read]},
       {[settings, indexes], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_external_access, [],
      [{name, <<"Query CURL Access">>},
       {folder, 'query'},
       {desc, <<"Can execute the CURL statement from within N1QL. This user "
                "can access the web console, but cannot read data (within "
                "Couchbase).">>}],
      [{[n1ql, curl], [execute]},
       {[{bucket, any}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_manage_global_functions, [],
      [{name, <<"Manage Global Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage global n1ql functions">>}],
      [{[n1ql, udf], [manage]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_global_functions, [],
      [{name, <<"Execute Global Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute global n1ql functions">>}],
      [{[n1ql, udf], [execute]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_manage_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scope Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage n1ql functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql, udf], [manage]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Execute Scope Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute n1ql functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql, udf], [execute]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_manage_global_external_functions, [],
      [{name, <<"Manage Global External Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage global external language functions">>}],
      [{[n1ql, udf_external], [manage]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_global_external_functions, [],
      [{name, <<"Execute Global External Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute global external language functions">>}],
      [{[n1ql, udf_external], [execute]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_manage_external_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scope External Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage external language functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql,
         udf_external], [manage]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_external_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Execute Scope External Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute external language functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql,
         udf_external], [execute]},
       {[ui], [read]},
       {[pools], [read]}]},
     {replication_target, [bucket_name],
      [{name, <<"XDCR Inbound">>},
       {folder, xdcr},
       {desc, <<"Can create XDCR streams into a given bucket. This user cannot "
                "access the web console.">>}],
      [{[{bucket, bucket_name}, settings], [read]},
       {[{bucket, bucket_name}, data, docs], [read]},
       {[{bucket, bucket_name}, data, meta], [write]},
       {[{bucket, bucket_name}, data, sxattr], [read, write]},
       {[{bucket, bucket_name}, stats], [read]},
       {[{bucket, bucket_name}, collections], [read]},
       {[pools], [read]}]},
     {analytics_manager, [bucket_name],
      [{name, <<"Analytics Manager">>},
       {folder, analytics},
       {desc, <<"Can manage Analytics local links. Can manage datasets on a "
                "given bucket. Can query datasets created on this bucket. "
                "This user can access the web console and read some data.">>}],
      [{[{bucket, bucket_name}, analytics], [manage, select]},
       {[ui], [read]},
       {[pools], [read]}]},
     {analytics_reader, [],
      [{name, <<"Analytics Reader">>},
       {folder, analytics},
       {desc, <<"Can query datasets. This is a global role as datasets may "
                "be created on different buckets. This user can access the "
                "web console and read some data.">>}],
      [{[analytics], [select]},
       {[{bucket, any}, analytics], [select]},
       {[ui], [read]},
       {[pools], [read]}]},
     {analytics_select, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Analytics Select">>},
       {folder, analytics},
       {desc, <<"Can query datasets on a given bucket, scope or "
                "collection. This user can access the web console and read "
                "some data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, analytics], [select]},
       {[ui], [read]},
       {[pools], [read]}]},
     {analytics_admin, [],
      [{name, <<"Analytics Admin">>},
       {folder, analytics},
       {desc, <<"Can manage dataverses. Can manage all Analytics links. "
                "Can manage all datasets. This user can access the web "
                "console but cannot read data.">>}],
      [{[analytics], [manage]},
       {[{bucket, any}, analytics], [manage]},
       {[ui], [read]},
       {[pools], [read]}]},
     {mobile_sync_gateway, [bucket_name],
      [{name, <<"Sync Gateway">>},
       {folder, mobile},
       {desc, <<"Full access to bucket data as required by Sync Gateway. "
                "This user cannot access the web console and is intended "
                "only for use by Sync Gateway. This user can read and "
                "write data, manage indexes and views, and read some "
                "cluster information.">>}],
      [{[{bucket, bucket_name}, data], all},
       {[{bucket, bucket_name}, views], all},
       {[{bucket, bucket_name}, n1ql, index], all},
       {[{bucket, bucket_name}, n1ql], [execute]},
       {[{bucket, bucket_name}], [read, flush]},
       {[{bucket, bucket_name}, settings], [read]},
       {[admin, memcached, idle], [write]},
       {[settings, autocompaction], [read]},
       {[pools], [read]}]},
     {sync_gateway_configurator, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Architect">>},
       {folder, mobile},
       {desc, <<"Can manage Sync Gateway databases and users, "
                "and access Sync Gateway's /metrics endpoint. "
                "This user cannot read application data.">>}],
      [{[{collection, [any, any, any]}, sgw, appdata], none},
       {[{collection, [any, any, any]}, sgw, principal_appdata], none},
       {[{collection, [any, any, any]}, sgw, replications], none},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw], all},
       {[admin, stats_export], [read]}]},
     {sync_gateway_app, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Application">>},
       {folder, mobile},
       {desc, <<"Can manage Sync Gateway users and roles, and "
                "read and write application data through Sync "
                "Gateway.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, auth], [configure]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal], [read, write]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, appdata], [read, write]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal_appdata], [read]}]},
     {sync_gateway_app_ro, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Application Read Only">>},
       {folder, mobile},
       {desc, <<"Can read Sync Gateway users and roles, and "
                "read application data through Sync Gateway.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, appdata], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal_appdata], [read]}]},
     {sync_gateway_replicator, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Replicator">>},
       {folder, mobile},
       {desc, <<"Can manage Inter-Sync Gateway Replications. "
                "This user cannot read application data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, replications], all}]},
     {sync_gateway_dev_ops, [],
      [{name, <<"Sync Gateway Dev Ops">>},
       {folder, mobile},
       {desc, <<"Can manage Sync Gateway node-level configuration, "
                "and access Sync Gateway's /metrics endpoint "
                "for Prometheus integration.">>}],
      [{[sgw, dev_ops], all},
       {[admin, stats_export], [read]}]},
     {external_stats_reader, [],
      [{name, <<"External Stats Reader">>},
       {folder, admin},
       {desc, <<"Access to /metrics endpoint for Prometheus integration. "
                "Can read all stats for all services. This user cannot "
                "access the web console">>}],
      [{[admin, stats_export], [read]}]},
     {eventing_manage_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scope Functions">>},
       {folder, eventing},
       {desc, <<"Can manage eventing functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, eventing, function], [manage]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[{bucket, bucket_name}, stats], [read]},
       {[ui], [read]},
       {[pools], [read]}]}].

-spec roles_pre_79() -> [rbac_role_def(), ...].
roles_pre_79() ->
    [{admin, [],
      [{name, <<"Full Admin">>},
       {folder, admin},
       {desc, <<"Can manage all cluster features (including security). "
                "This user can access the web console. This user can read and "
                "write all data.">>},
       {ce, true}],
      [{[], all}]},
     {ro_admin, [],
      [{name, <<"Read-Only Admin">>},
       {folder, admin},
       {desc, <<"Can view all cluster statistics. This user can access the "
                "web console.">>},
       {ce, true}],
      [{[{bucket, any}, data], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[admin, security], [read]},
       {[admin, stats_export], [read]},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], [read]},
       {[], [read, list]}]},
     {security_admin_local, [],
      [{name, <<"Local User Security Admin">>},
       {folder, admin},
       {desc, <<"Can view all cluster statistics and manage local user "
                "roles, but not grant Full Admin or Security Admin roles to "
                "other users or alter their own role. This user can access "
                "the web console. This user cannot read data.">>}],
      [{[admin, security, admin], none},
       {[admin, security, external], none},
       {[admin, security], all},
       {[admin, logs], none},
       {[admin, event], none},
       {[admin, metakv], none},
       {[admin, settings, metrics], none},
       {[{bucket, any}, data], none},
       {[{bucket, any}, views], none},
       {[{bucket, any}, n1ql], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[{bucket, any}], [read]},
       {[analytics], none},
       {[backup], none},
       {[eventing], none},
       {[xdcr], none},
       {[settings, fts], none},
       {[settings, metrics], none},
       {[], [read, list]}]},
     {security_admin_external, [],
      [{name, <<"External User Security Admin">>},
       {folder, admin},
       {desc, <<"Can view all cluster statistics and manage external user "
                "roles, but not grant Full Admin or Security Admin roles to "
                "other users or alter their own role. This user can access "
                "the web console. This user cannot read data.">>}],
      [{[admin, security, admin], none},
       {[admin, security, local], none},
       {[admin, security], all},
       {[admin, logs], none},
       {[admin, event], none},
       {[admin, metakv], none},
       {[admin, settings], none},
       {[{bucket, any}, data], none},
       {[{bucket, any}, views], none},
       {[{bucket, any}, n1ql], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[{bucket, any}], [read]},
       {[analytics], none},
       {[backup], none},
       {[eventing], none},
       {[xdcr], none},
       {[settings, fts], none},
       {[], [read, list]}]},
     {cluster_admin, [],
      [{name, <<"Cluster Admin">>},
       {folder, admin},
       {desc, <<"Can manage all cluster features except security. This user "
                "can access the web console. This user cannot read data.">>}],
      [{[admin, internal], none},
       {[admin, security], none},
       {[admin, diag], [read]},
       {[admin, event], none},
       {[admin, metakv], none},
       {[admin, settings, metrics], none},
       {[{bucket, any}, data], none},
       {[{bucket, any}, views], none},
       {[{bucket, any}, n1ql], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[n1ql, curl], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[], all}]},
     {eventing_admin, [],
      [{name, <<"Eventing Full Admin">>},
       {folder, admin},
       {desc, <<"Can create/manage eventing functions. This user can access "
                "the web console">>}],
      [{[admin], none},
       {[xdcr], none},
       {[{bucket, any}, xdcr], none},
       %% This role is intentionally given this powerful permission
       %% (see MB-42835).
       {[{bucket, any}], all},
       {[n1ql], all},
       {[eventing], all},
       {[analytics], all},
       {[buckets], all},
       {[settings, metrics], none},
       {[], [read]}]},
     {backup_admin, [],
      [{name, <<"Backup Full Admin">>},
       {folder, admin},
       {desc, <<"Can perform backup related tasks. This user can access "
                "the web console">>}],
      [{[admin], none},
       {[settings, metrics], none},
       {[], all}]},
     {bucket_admin, [bucket_name],
      [{name, <<"Bucket Admin">>},
       {folder, bucket},
       {desc, <<"Can manage ALL bucket features for a given bucket (including "
                "start/stop XDCR). This user can access the web console. This "
                "user cannot read data.">>}],
      [{[{bucket, bucket_name}, xdcr], [read, execute]},
       {[{bucket, bucket_name}, data], none},
       {[{bucket, bucket_name}, views], none},
       {[{bucket, bucket_name}, n1ql], none},
       {[{bucket, bucket_name}, fts], none},
       {[{bucket, any}, analytics], none},
       {[{bucket, bucket_name}], all},
       {[{bucket, any}, settings], [read]},
       {[{bucket, any}], none},
       {[xdcr], none},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[settings, metrics], none},
       {[n1ql, meta], [none]},
       {[], [read]}]},
     {scope_admin, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scopes">>},
       {folder, bucket},
       {desc, <<"Can create/delete scopes and collections within a given "
                "bucket. This user cannot access the web console.">>}],
      [{[{collection, [bucket_name, scope_name, any]}, collections], all}]},
     {bucket_full_access, [bucket_name],
      [{name, <<"Application Access">>},
       {folder, bucket},
       {desc, <<"Full access to bucket data. This user cannot access the web "
                "console and is intended only for application access. This "
                "user can read and write data except for the _system scope "
                "which can only be read.">>},
       {ce, true}],
      [{[{bucket, bucket_name}, data, docs], [read, insert, delete, upsert,
                                             range_scan, sread]},
       {[{bucket, bucket_name}, data], all},
       {[{bucket, bucket_name}, views], all},
       {[{bucket, bucket_name}, n1ql, index], all},
       {[{bucket, bucket_name}, n1ql], [execute]},
       {[{bucket, bucket_name}], [read, flush]},
       {[{bucket, bucket_name}, settings], [read]},
       {[pools], [read]}]},
     {views_admin, [bucket_name],
      [{name, <<"Views Admin">>},
       {folder, admin},
       {desc, <<"Can create and manage views of a given bucket. This user can "
                "access the web console. This user can read some data.">>}],
      [{[{bucket, bucket_name}, views], all},
       {[{bucket, bucket_name}, data, docs], [read, sread]},
       {[{bucket, bucket_name}, data], [read]},
       {[{bucket, bucket_name}, stats], [read]},
       {[{bucket, any}, settings], [read]},
       {[{bucket, any}], none},
       {[{bucket, bucket_name}, n1ql], [execute]},
       {[xdcr], none},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[settings, metrics], none},
       {[], [read]}]},
     {views_reader, [bucket_name],
      [{name, <<"Views Reader">>},
       {folder, views},
       {desc, <<"Can read data from the views of a given bucket. This user "
                "cannot access the web console and is intended only for "
                "application access. This user can read some data.">>}],
      [{[{bucket, bucket_name}, views], [read]},
       {[{bucket, bucket_name}, data, docs], [read, sread]},
       {[pools], [read]}]},
     {replication_admin, [],
      [{name, <<"XDCR Admin">>},
       {folder, xdcr},
       {desc, <<"Can administer XDCR features to create cluster references and "
                "replication streams out of this cluster. This user can "
                "access the web console. This user can read some data.">>}],
      [{[{bucket, any}, xdcr], all},
       {[{bucket, any}, data, docs], [read, sread]},
       {[{bucket, any}, data], [read]},
       {[{bucket, any}, settings], [read]},
       {[{bucket, any}, stats], [read]},
       {[{bucket, any}, collections], [read]},
       {[{bucket, any}], none},
       {[xdcr, developer], [read]},
       {[xdcr], all},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[settings, metrics], none},
       {[], [read]}]},
     {data_reader, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data Reader">>},
       {folder, data},
       {desc, <<"Can read data from a given bucket, scope or collection. "
                "This user cannot access the web console and is intended only "
                "for application access. This user can read data, but cannot "
                "write it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs],
        [read, range_scan, sread]},
       {[{bucket, bucket_name}, settings], [read]},
       {[pools], [read]}]},
     {data_writer, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data Writer">>},
       {folder, data},
       {desc, <<"Can write data to a given bucket, scope or collection. "
                "This user cannot access the web console and is intended only "
                "for application access. This user can write data, but cannot "
                "read it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs],
        [insert, upsert, delete]},
       {[{bucket, bucket_name}, settings], [read]},
       {[pools], [read]}]},
     {data_dcp_reader, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data DCP Reader">>},
       {folder, data},
       {desc, <<"Can initiate DCP streams for a given bucket, scope or "
                "collection. This user cannot access the web console and is "
                "intended only for application access. "
                "This user can read data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [read, sread]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, dcpstream], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, sxattr], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, collections], [read]},
       {[{bucket, bucket_name}, data, dcp], [read]},
       {[{bucket, bucket_name}, data, docs], [sread]},
       {[{bucket, bucket_name}, settings], [read]},
       {[admin, memcached, idle], [write]},
       {[pools], [read]}]},
     {data_backup, [bucket_name],
      [{name, <<"Data Backup & Restore">>},
       {folder, backup},
       {desc, <<"Can backup and restore a given bucket’s data. This user "
                "cannot access the web console and is intended only for "
                "application access. This user can read data.">>}],
      [{[{collection, [bucket_name, any, any]}, collections], all},
       {[{bucket, bucket_name}, data], all},
       {[{bucket, bucket_name}, views], [read, write]},
       {[{bucket, bucket_name}, fts], [read, write, manage]},
       {[{bucket, bucket_name}, stats], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[{bucket, bucket_name}, n1ql, index], [create, list, build]},
       {[{bucket, bucket_name}, n1ql, meta], [backup]},
       {[{bucket, bucket_name}, analytics], [manage, select]},
       {[analytics], [select, backup]},
       {[pools], [read]}]},
     {data_monitoring, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data Monitor">>},
       {folder, data},
       {desc, <<"Can read statistics for a given bucket, scope or collection. "
                "This user cannot access the web console and is intended only "
                "for application access. This user cannot read data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, stats], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, collections], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[tasks], [read]},
       {[pools], [read]}]},
     {fts_admin, [bucket_name],
      [{name, <<"Search Admin">>},
       {folder, search},
       {desc, <<"Can administer all Full Text Search features. This user can "
                "access the web console. This user can read some data.">>}],
      [{[{bucket, bucket_name}, fts], [read, write, manage]},
       {[{bucket, bucket_name}, collections], [read]},
       {[{bucket, bucket_name}, data, docs], [read, sread]},
       {[settings, fts], [read, write, manage]},
       {[ui], [read]},
       {[pools], [read]},
       {[{bucket, bucket_name}, settings], [read]}]},
     {fts_searcher, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Search Reader">>},
       {folder, search},
       {desc, <<"Can query Full Text Search indexes for a given bucket, scope "
                "or collection. This user can access the web console. This "
                "user can read some data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, fts], [read]},
       {[settings, fts], [read]},
       {[ui], [read]},
       {[pools], [read]},
       {[{bucket, bucket_name}, settings], [read]}]},
     {query_select, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Select">>},
       {folder, 'query'},
       {desc, <<"Can execute a SELECT statement on a given bucket, scope or "
                "collection to retrieve data. This user can access the web "
                "console and can read data, but not write it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, select], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [read, sread]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_update, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Update">>},
       {folder, 'query'},
       {desc, <<"Can execute an UPDATE statement on a given bucket, scope or "
                "collection to update data. This user can access the web "
                "console and write data, but cannot read it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, update], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs],
        [upsert, range_scan]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_insert, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Insert">>},
       {folder, 'query'},
       {desc, <<"Can execute an INSERT statement on a given bucket, scope or "
                "collection to add data. This user can access the web console "
                "and insert data, but cannot read it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, insert], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [insert]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_delete, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Delete">>},
       {folder, 'query'},
       {desc, <<"Can execute a DELETE statement on a given bucket, scope or "
                "collection to delete data. This user can access the web "
                "console, but cannot read data. This user can delete data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, delete], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs],
        [delete, range_scan]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_manage_index, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Manage Index">>},
       {folder, 'query'},
       {desc, <<"Can manage indexes for a given bucket, scope or collection. "
                "This user can access the web console, can read statistics "
                "for a given bucket, scope or collection. This user cannot "
                "read data.">>
       }],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, index], all},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, collections], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[{bucket, bucket_name}, stats], [read]},
       {[settings, indexes], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_system_catalog, [],
      [{name, <<"Query System Catalog">>},
       {folder, 'query'},
       {desc, <<"Can look up system catalog information via N1QL. This user "
                "can access the web console, but cannot read user data.">>}],
      [{[{bucket, any}, n1ql, index], [list]},
       {[{bucket, any}, settings], [read]},
       {[n1ql, meta], [read]},
       {[settings, indexes], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_external_access, [],
      [{name, <<"Query CURL Access">>},
       {folder, 'query'},
       {desc, <<"Can execute the CURL statement from within N1QL. This user "
                "can access the web console, but cannot read data (within "
                "Couchbase).">>}],
      [{[n1ql, curl], [execute]},
       {[{bucket, any}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_manage_global_functions, [],
      [{name, <<"Manage Global Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage global n1ql functions">>}],
      [{[n1ql, udf], [manage]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_global_functions, [],
      [{name, <<"Execute Global Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute global n1ql functions">>}],
      [{[n1ql, udf], [execute]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_manage_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scope Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage n1ql functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql, udf], [manage]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Execute Scope Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute n1ql functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql, udf], [execute]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_manage_global_external_functions, [],
      [{name, <<"Manage Global External Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage global external language functions">>}],
      [{[n1ql, udf_external], [manage]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_global_external_functions, [],
      [{name, <<"Execute Global External Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute global external language functions">>}],
      [{[n1ql, udf_external], [execute]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_manage_external_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scope External Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage external language functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql,
         udf_external], [manage]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_external_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Execute Scope External Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute external language functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql,
         udf_external], [execute]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_manage_sequences, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Sequences">>},
       {folder, 'query'},
       {desc, <<"Can manage sequences for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql, sequences],
        [manage]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_use_sequences, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Use Sequences">>},
       {folder, 'query'},
       {desc, <<"Can use sequences for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql, sequences],
        [execute]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_use_sequential_scans, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Use Sequential Scans">>},
       {folder, 'query'},
       {desc, <<"Can use sequential scans for access to a given bucket, scope "
                "or collection.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, sequential_scan],
        [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [range_scan]}]},
     {replication_target, [bucket_name],
      [{name, <<"XDCR Inbound">>},
       {folder, xdcr},
       {desc, <<"Can create XDCR streams into a given bucket. This user cannot "
                "access the web console.">>}],
      [{[{bucket, bucket_name}, settings], [read]},
       {[{bucket, bucket_name}, data, docs], [read, sread]},
       {[{bucket, bucket_name}, data, meta], [write]},
       {[{bucket, bucket_name}, data, sxattr], [read, write]},
       {[{bucket, bucket_name}, stats], [read]},
       {[{bucket, bucket_name}, collections], [read]},
       {[pools], [read]}]},
     {analytics_manager, [bucket_name],
      [{name, <<"Analytics Manager">>},
       {folder, analytics},
       {desc, <<"Can manage Analytics local links. Can manage datasets on a "
                "given bucket. Can query datasets created on this bucket. "
                "This user can access the web console and read some data.">>}],
      [{[{bucket, bucket_name}, analytics], [manage, select]},
       {[ui], [read]},
       {[pools], [read]}]},
     {analytics_reader, [],
      [{name, <<"Analytics Reader">>},
       {folder, analytics},
       {desc, <<"Can query datasets. This is a global role as datasets may "
                "be created on different buckets. This user can access the "
                "web console and read some data.">>}],
      [{[analytics], [select]},
       {[{bucket, any}, analytics], [select]},
       {[ui], [read]},
       {[pools], [read]}]},
     {analytics_select, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Analytics Select">>},
       {folder, analytics},
       {desc, <<"Can query datasets on a given bucket, scope or "
                "collection. This user can access the web console and read "
                "some data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, analytics], [select]},
       {[ui], [read]},
       {[pools], [read]}]},
     {analytics_admin, [],
      [{name, <<"Analytics Admin">>},
       {folder, analytics},
       {desc, <<"Can manage dataverses. Can manage all Analytics links. "
                "Can manage all datasets. This user can access the web "
                "console but cannot read data.">>}],
      [{[analytics], [manage]},
       {[{bucket, any}, analytics], [manage]},
       {[ui], [read]},
       {[pools], [read]}]},
     {mobile_sync_gateway, [bucket_name],
      [{name, <<"Sync Gateway">>},
       {folder, mobile},
       {desc, <<"Full access to bucket data as required by Sync Gateway. "
                "This user cannot access the web console and is intended "
                "only for use by Sync Gateway. This user can read and "
                "write data, manage indexes and views, and read some "
                "cluster information.">>}],
      [{[{collection, [bucket_name, ?SYSTEM_SCOPE_NAME, "_mobile"]}, data],
        all},
       {[{bucket, bucket_name}, data, docs], [read, insert, delete, upsert,
                                              range_scan, sread]},
       {[{bucket, bucket_name}, data], all},
       {[{bucket, bucket_name}, views], all},
       {[{bucket, bucket_name}, n1ql, index], all},
       {[{bucket, bucket_name}, n1ql], [execute]},
       {[{bucket, bucket_name}], [read, flush]},
       {[{bucket, bucket_name}, settings], [read]},
       {[admin, memcached, idle], [write]},
       {[settings, autocompaction], [read]},
       {[pools], [read]}]},
     {sync_gateway_configurator, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Architect">>},
       {folder, mobile},
       {desc, <<"Can manage Sync Gateway databases and users, "
                "and access Sync Gateway's /metrics endpoint. "
                "This user cannot read application data.">>}],
      [{[{collection, [any, any, any]}, sgw, appdata], none},
       {[{collection, [any, any, any]}, sgw, principal_appdata], none},
       {[{collection, [any, any, any]}, sgw, replications], none},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw], all},
       {[admin, stats_export], [read]}]},
     {sync_gateway_app, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Application">>},
       {folder, mobile},
       {desc, <<"Can manage Sync Gateway users and roles, and "
                "read and write application data through Sync "
                "Gateway.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, auth], [configure]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal], [read, write]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, appdata], [read, write]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal_appdata],
        [read]}]},
     {sync_gateway_app_ro, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Application Read Only">>},
       {folder, mobile},
       {desc, <<"Can read Sync Gateway users and roles, and "
                "read application data through Sync Gateway.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, appdata], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal_appdata],
        [read]}]},
     {sync_gateway_replicator, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Replicator">>},
       {folder, mobile},
       {desc, <<"Can manage Inter-Sync Gateway Replications. "
                "This user cannot read application data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, replications], all}]},
     {sync_gateway_dev_ops, [],
      [{name, <<"Sync Gateway Dev Ops">>},
       {folder, mobile},
       {desc, <<"Can manage Sync Gateway node-level configuration, "
                "and access Sync Gateway's /metrics endpoint "
                "for Prometheus integration.">>}],
      [{[sgw, dev_ops], all},
       {[admin, stats_export], [read]}]},
     {external_stats_reader, [],
      [{name, <<"External Stats Reader">>},
       {folder, admin},
       {desc, <<"Access to /metrics endpoint for Prometheus integration. "
                "Can read all stats for all services. This user cannot "
                "access the web console">>}],
      [{[admin, stats_export], [read]}]},
     {eventing_manage_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scope Functions">>},
       {folder, eventing},
       {desc, <<"Can manage eventing functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, eventing, function],
        [manage]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[{bucket, bucket_name}, stats], [read]},
       {[ui], [read]},
       {[pools], [read]}]}
    ].

-spec roles_pre_totoro() -> [rbac_role_def(), ...].
roles_pre_totoro() ->
    [{admin, [],
      [{name, <<"Full Admin">>},
       {folder, admin},
       {desc, <<"Can manage all cluster features (including security). "
                "This user can access the web console. This user can read and "
                "write all data.">>},
       {ce, true}],
      [{[], all}]},
     {ro_admin, [],
      [{name, <<"Read-Only Admin">>},
       {folder, admin},
       {desc, <<"Can view all cluster statistics. This user can access the "
                "web console. This user cannot read security-related "
                "information, including listing users or groups.">>},
       {ce, true}],
      [{[{bucket, any}, data], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[admin, security], none},
       {[admin, security_info], none},
       {[admin, stats_export], [read]},
       {[admin, users], none},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], [read]},
       {[], [read, list]}]},
     {security_admin, [],
      [{name, <<"Security Admin">>},
       {folder, admin},
       {desc, <<"Can view all cluster statistics, manage certificates, and "
                "manage security related settings. This user can access the "
                "web console. This user cannot read data.">>}],
      [{[admin, security, admin], none},
       {[admin, security], all},
       {[admin, security_info], all},
       {[admin, users], [read]},
       {[admin, logs], none},
       {[admin, event], none},
       {[admin, metakv], none},
       {[admin, settings, metrics], none},
       {[{bucket, any}, data], none},
       {[{bucket, any}, views], none},
       {[{bucket, any}, n1ql], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[{bucket, any}], [read]},
       {[analytics], none},
       {[backup], none},
       {[eventing], none},
       {[xdcr], none},
       {[settings, fts], none},
       {[settings, metrics], none},
       {[], [read, list]}]},
     {ro_security_admin, [],
      [{name, <<"Read-Only Security Admin">>},
       {folder, admin},
       {desc, <<"Can view all cluster statistics. Can read security related "
                "settings but cannot change them. This user can access the "
                "web console. This user cannot read data.">>}],
      [{[admin, security, admin], none},
       {[admin, security], [read]},
       {[admin, security_info], [read]},
       {[admin, users], [read]},
       {[admin, logs], none},
       {[admin, event], none},
       {[admin, metakv], none},
       {[admin, settings, metrics], none},
       {[{bucket, any}, data], none},
       {[{bucket, any}, views], none},
       {[{bucket, any}, n1ql], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[{bucket, any}], [read]},
       {[analytics], none},
       {[backup], none},
       {[eventing], none},
       {[xdcr], none},
       {[settings, fts], none},
       {[settings, metrics], none},
       {[], [read, list]}]},
     {user_admin_local, [],
      [{name, <<"Local User Admin">>},
       {folder, admin},
       {desc, <<"Can view all cluster statistics and manage local user "
                "roles, but not grant Full Admin or Security Admin roles to "
                "other users or itself. This user can access the web console. "
                "This user cannot read data.">>}],
      [{[admin, security, admin], none},
       {[admin, security], none},
       {[admin, security_info], [read, write]},
       {[admin, users, admin], none},
       {[admin, users, external], none},
       {[admin, users], all},
       {[admin, logs], none},
       {[admin, event], none},
       {[admin, metakv], none},
       {[admin, settings, metrics], none},
       {[{bucket, any}, data], none},
       {[{bucket, any}, views], none},
       {[{bucket, any}, n1ql], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[{bucket, any}], [read]},
       {[analytics], none},
       {[backup], none},
       {[eventing], none},
       {[xdcr], none},
       {[settings, fts], none},
       {[settings, metrics], none},
       {[], [read, list]}]},
     {user_admin_external, [],
      [{name, <<"External User Admin">>},
       {folder, admin},
       {desc, <<"Can view all cluster statistics and manage external user "
                "roles, but not grant Full Admin or Security Admin roles to "
                "other users or itself. This user can access the web console. "
                "This user cannot read data.">>}],
      [{[admin, security, admin], none},
       {[admin, security], none},
       {[admin, security_info], [read, write]},
       {[admin, users, admin], none},
       {[admin, users, local], none},
       {[admin, users], all},
       {[admin, logs], none},
       {[admin, event], none},
       {[admin, metakv], none},
       {[admin, settings], none},
       {[{bucket, any}, data], none},
       {[{bucket, any}, views], none},
       {[{bucket, any}, n1ql], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[{bucket, any}], [read]},
       {[analytics], none},
       {[backup], none},
       {[eventing], none},
       {[xdcr], none},
       {[settings, fts], none},
       {[settings, metrics], none},
       {[], [read, list]}]},
     {cluster_admin, [],
      [{name, <<"Cluster Admin">>},
       {folder, admin},
       {desc, <<"Can manage all cluster features except security and users. "
                "This user can access the web console. This user cannot read "
                "data.">>}],
      [{[admin, internal], none},
       {[admin, security], none},
       {[admin, security_info], none},
       {[admin, users], none},
       {[admin, diag], [read]},
       {[admin, event], none},
       {[admin, metakv], none},
       {[admin, settings, metrics], none},
       {[{bucket, any}, data], none},
       {[{bucket, any}, views], none},
       {[{bucket, any}, n1ql], none},
       {[{bucket, any}, fts], none},
       {[{bucket, any}, analytics], none},
       {[n1ql, curl], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[], all}]},
     {eventing_admin, [],
      [{name, <<"Eventing Full Admin">>},
       {folder, admin},
       {desc, <<"Can create/manage eventing functions. This user can access "
                "the web console">>}],
      [{[admin], none},
       {[xdcr], none},
       {[{bucket, any}, xdcr], none},
       %% This role is intentionally given this powerful permission
       %% (see MB-42835).
       {[{bucket, any}], all},
       {[n1ql], all},
       {[eventing], all},
       {[analytics], all},
       {[buckets], all},
       {[settings, metrics], none},
       {[], [read]}]},
     {backup_admin, [],
      [{name, <<"Backup Full Admin">>},
       {folder, admin},
       {desc, <<"Can perform backup related tasks. This user can access "
                "the web console">>}],
      [{[admin], none},
       {[settings, metrics], none},
       {[], all}]},
     {bucket_admin, [bucket_name],
      [{name, <<"Bucket Admin">>},
       {folder, bucket},
       {desc, <<"Can manage ALL bucket features for a given bucket (including "
                "start/stop XDCR). This user can access the web console. This "
                "user cannot read data.">>}],
      [{[{bucket, bucket_name}, xdcr], [read, execute]},
       {[{bucket, bucket_name}, data], none},
       {[{bucket, bucket_name}, views], none},
       {[{bucket, bucket_name}, n1ql], none},
       {[{bucket, bucket_name}, fts], none},
       {[{bucket, any}, analytics], none},
       {[{bucket, bucket_name}], all},
       {[{bucket, any}, settings], [read]},
       {[{bucket, any}], none},
       {[xdcr], none},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[settings, metrics], none},
       {[n1ql, meta], none},
       {[], [read]}]},
     {scope_admin, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scopes">>},
       {folder, bucket},
       {desc, <<"Can create/delete scopes and collections within a given "
                "bucket. This user cannot access the web console.">>}],
      [{[{collection, [bucket_name, scope_name, any]}, collections], all}]},
     {bucket_full_access, [bucket_name],
      [{name, <<"Application Access">>},
       {folder, bucket},
       {desc, <<"Full access to bucket data. This user cannot access the web "
                "console and is intended only for application access. This "
                "user can read and write data except for the _system scope "
                "which can only be read.">>},
       {ce, true}],
      [{[{bucket, bucket_name}, data, docs], [read, insert, delete, upsert,
                                              range_scan, sread]},
       {[{bucket, bucket_name}, data], all},
       {[{bucket, bucket_name}, views], all},
       {[{bucket, bucket_name}, n1ql, index], all},
       {[{bucket, bucket_name}, n1ql], [execute]},
       {[{bucket, bucket_name}], [read, flush]},
       {[{bucket, bucket_name}, settings], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {views_admin, [bucket_name],
      [{name, <<"Views Admin">>},
       {folder, admin},
       {desc, <<"Can create and manage views of a given bucket. This user can "
                "access the web console. This user can read some data.">>}],
      [{[{bucket, bucket_name}, views], all},
       {[{bucket, bucket_name}, data, docs], [read, sread]},
       {[{bucket, bucket_name}, data], [read]},
       {[{bucket, bucket_name}, stats], [read]},
       {[{bucket, any}, settings], [read]},
       {[{bucket, any}], none},
       {[{bucket, bucket_name}, n1ql], [execute]},
       {[xdcr], none},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[settings, metrics], none},
       {[], [read]}]},
     {views_reader, [bucket_name],
      [{name, <<"Views Reader">>},
       {folder, views},
       {desc, <<"Can read data from the views of a given bucket. This user "
                "cannot access the web console and is intended only for "
                "application access. This user can read some data.">>}],
      [{[{bucket, bucket_name}, views], [read]},
       {[{bucket, bucket_name}, data, docs], [read, sread]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {replication_admin, [],
      [{name, <<"XDCR Admin">>},
       {folder, xdcr},
       {desc, <<"Can administer XDCR features to create cluster references and "
                "replication streams out of this cluster. This user can "
                "access the web console. This user can read some data.">>}],
      [{[{bucket, any}, xdcr], all},
       {[{bucket, any}, data, docs], [read, sread]},
       {[{bucket, any}, data], [read]},
       {[{bucket, any}, settings], [read]},
       {[{bucket, any}, stats], [read]},
       {[{bucket, any}, collections], [read]},
       {[{bucket, any}], none},
       {[xdcr, developer], [read]},
       {[xdcr], all},
       {[admin], none},
       {[eventing], none},
       {[analytics], none},
       {[backup], none},
       {[settings, metrics], none},
       {[], [read]}]},
     {data_reader, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data Reader">>},
       {folder, data},
       {desc, <<"Can read data from a given bucket, scope or collection. "
                "This user cannot access the web console and is intended only "
                "for application access. This user can read data, but cannot "
                "write it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs],
        [read, range_scan, sread]},
       {[{bucket, bucket_name}, settings], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {data_writer, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data Writer">>},
       {folder, data},
       {desc, <<"Can write data to a given bucket, scope or collection. "
                "This user cannot access the web console and is intended only "
                "for application access. This user can write data, but cannot "
                "read it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs],
        [insert, upsert, delete]},
       {[{bucket, bucket_name}, settings], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {data_dcp_reader, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data DCP Reader">>},
       {folder, data},
       {desc, <<"Can initiate DCP streams for a given bucket, scope or "
                "collection. This user cannot access the web console and is "
                "intended only for application access. "
                "This user can read data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [read, sread]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, dcpstream], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, sxattr], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, collections], [read]},
       {[{bucket, bucket_name}, data, dcp], [read]},
       {[{bucket, bucket_name}, data, docs], [sread]},
       {[{bucket, bucket_name}, settings], [read]},
       {[admin, memcached, idle], [write]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {data_backup, [bucket_name],
      [{name, <<"Data Backup & Restore">>},
       {folder, backup},
       {desc, <<"Can backup and restore a given bucket’s data. This user "
                "cannot access the web console and is intended only for "
                "application access. This user can read data.">>}],
      [{[{collection, [bucket_name, any, any]}, collections], all},
       {[{bucket, bucket_name}, data], all},
       {[{bucket, bucket_name}, views], [read, write]},
       {[{bucket, bucket_name}, fts], [read, write, manage]},
       {[{bucket, bucket_name}, stats], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[{bucket, bucket_name}, n1ql, index], [create, list, build]},
       {[{bucket, bucket_name}, n1ql, meta], [backup]},
       {[{bucket, bucket_name}, analytics], [manage, select]},
       {[analytics], [select, backup]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {data_monitoring, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Data Monitor">>},
       {folder, data},
       {desc, <<"Can read statistics for a given bucket, scope or collection. "
                "This user cannot access the web console and is intended only "
                "for application access. This user cannot read data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, stats], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, collections], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[tasks], [read]},
       {[pools], [read]}]},
     {fts_admin, [bucket_name],
      [{name, <<"Search Admin">>},
       {folder, search},
       {desc, <<"Can administer all Full Text Search features. This user can "
                "access the web console. This user can read some data.">>}],
      [{[{bucket, bucket_name}, fts], [read, write, manage]},
       {[{bucket, bucket_name}, collections], [read]},
       {[{bucket, bucket_name}, data, docs], [read, sread]},
       {[settings, fts], [read, write, manage]},
       {[ui], [read]},
       {[pools], [read]},
       {[{bucket, bucket_name}, settings], [read]}]},
     {fts_searcher, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Search Reader">>},
       {folder, search},
       {desc, <<"Can query Full Text Search indexes for a given bucket, scope "
                "or collection. This user can access the web console. This "
                "user can read some data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, fts], [read]},
       {[settings, fts], [read]},
       {[ui], [read]},
       {[pools], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[app_telemetry], [write]}]},
     {query_select, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Select">>},
       {folder, 'query'},
       {desc, <<"Can execute a SELECT statement on a given bucket, scope or "
                "collection to retrieve data. This user can access the web "
                "console and can read data, but not write it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, select], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [read, sread]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {query_update, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Update">>},
       {folder, 'query'},
       {desc, <<"Can execute an UPDATE statement on a given bucket, scope or "
                "collection to update data. This user can access the web "
                "console and write data, but cannot read it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, update], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs],
        [upsert, range_scan]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {query_insert, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Insert">>},
       {folder, 'query'},
       {desc, <<"Can execute an INSERT statement on a given bucket, scope or "
                "collection to add data. This user can access the web console "
                "and insert data, but cannot read it.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, insert], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [insert]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {query_delete, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Delete">>},
       {folder, 'query'},
       {desc, <<"Can execute a DELETE statement on a given bucket, scope or "
                "collection to delete data. This user can access the web "
                "console, but cannot read data. This user can delete data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, delete], [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs],
        [delete, range_scan]},
       {[{bucket, bucket_name}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {query_manage_index, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Manage Index">>},
       {folder, 'query'},
       {desc, <<"Can manage indexes for a given bucket, scope or collection. "
                "This user can access the web console, can read statistics "
                "for a given bucket, scope or collection. This user cannot "
                "read data.">>
       }],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, index], all},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, collections], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[{bucket, bucket_name}, stats], [read]},
       {[settings, indexes], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_list_index, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query List Index">>},
       {folder, 'query'},
       {desc, <<"Can list indexes for a given bucket, scope or collection. "
                "This user can access the web console, can read statistics "
                "for a given bucket, scope or collection. This user cannot "
                "read data.">>
       }],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, index], [list, read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, collections], [read]},
       {[{bucket, bucket_name}, settings], [read]},
       {[{bucket, bucket_name}, stats], [read]},
       {[settings, indexes], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_system_catalog, [],
      [{name, <<"Query System Catalog">>},
       {folder, 'query'},
       {desc, <<"Can look up system catalog information via N1QL. This user "
                "can access the web console, but cannot read user data.">>}],
      [{[{bucket, any}, n1ql, index], [list]},
       {[{bucket, any}, settings], [read]},
       {[n1ql, meta], [read]},
       {[settings, indexes], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_external_access, [],
      [{name, <<"Query CURL Access">>},
       {folder, 'query'},
       {desc, <<"Can execute the CURL statement from within N1QL. This user "
                "can access the web console, but cannot read data (within "
                "Couchbase).">>}],
      [{[n1ql, curl], [execute]},
       {[{bucket, any}, settings], [read]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {query_manage_global_functions, [],
      [{name, <<"Manage Global Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage global n1ql functions">>}],
      [{[n1ql, udf], [manage]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_global_functions, [],
      [{name, <<"Execute Global Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute global n1ql functions">>}],
      [{[n1ql, udf], [execute]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {query_manage_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scope Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage n1ql functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql, udf], [manage]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Execute Scope Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute n1ql functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql, udf], [execute]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {query_manage_global_external_functions, [],
      [{name, <<"Manage Global External Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage global external language functions">>}],
      [{[n1ql, udf_external], [manage]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_global_external_functions, [],
      [{name, <<"Execute Global External Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute global external language functions">>}],
      [{[n1ql, udf_external], [execute]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {query_manage_external_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scope External Functions">>},
       {folder, 'query'},
       {desc, <<"Can manage external language functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql,
         udf_external], [manage]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_execute_external_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Execute Scope External Functions">>},
       {folder, 'query'},
       {desc, <<"Can execute external language functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql,
         udf_external], [execute]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {query_manage_sequences, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Sequences">>},
       {folder, 'query'},
       {desc, <<"Can manage sequences for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql, sequences],
        [manage]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[ui], [read]},
       {[pools], [read]}]},
     {query_use_sequences, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Use Sequences">>},
       {folder, 'query'},
       {desc, <<"Can use sequences for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, n1ql, sequences],
        [execute]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {query_use_sequential_scans, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Query Use Sequential Scans">>},
       {folder, 'query'},
       {desc, <<"Can use sequential scans for access to a given bucket, scope "
                "or collection.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, n1ql, sequential_scan],
        [execute]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, data, docs], [range_scan]},
       {[app_telemetry], [write]}]},
     {query_manage_system_catalog, [],
      [{name, <<"Query Manage System Catalog">>},
       {folder, query},
       {desc, <<"Can manage Query system catalogs via SQL++. "
                "This user can access the web console. This user cannot "
                "read data.">>}],
      [{[n1ql, meta], [manage]},
       {[ui], [read]},
       {[pools], [read]}]},
     {replication_target, [bucket_name],
      [{name, <<"XDCR Inbound">>},
       {folder, xdcr},
       {desc, <<"Can create XDCR streams into a given bucket. This user cannot "
                "access the web console.">>}],
      [{[{bucket, bucket_name}, settings], [read]},
       {[{bucket, bucket_name}, data, docs], [read, sread, upsert]},
       {[{bucket, bucket_name}, data, meta], [write]},
       {[{bucket, bucket_name}, data, sxattr], [read, write]},
       {[{bucket, bucket_name}, stats], [read]},
       {[{bucket, bucket_name}, collections], [read]},
       {[xdcr, c2c_communications], all},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {analytics_manager, [bucket_name],
      [{name, <<"Analytics Manager">>},
       {folder, analytics},
       {desc, <<"Can manage Analytics local links. Can manage datasets on a "
                "given bucket. Can query datasets created on this bucket. "
                "This user can access the web console and read some data.">>}],
      [{[{bucket, bucket_name}, analytics], [manage, select]},
       {[ui], [read]},
       {[pools], [read]}]},
     {analytics_reader, [],
      [{name, <<"Analytics Reader">>},
       {folder, analytics},
       {desc, <<"Can query datasets. This is a global role as datasets may "
                "be created on different buckets. This user can access the "
                "web console and read some data.">>}],
      [{[analytics], [select]},
       {[{bucket, any}, analytics], [select]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {analytics_select, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Analytics Select">>},
       {folder, analytics},
       {desc, <<"Can query datasets on a given bucket, scope or "
                "collection. This user can access the web console and read "
                "some data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, analytics], [select]},
       {[ui], [read]},
       {[pools], [read]},
       {[app_telemetry], [write]}]},
     {analytics_admin, [],
      [{name, <<"Analytics Admin">>},
       {folder, analytics},
       {desc, <<"Can manage dataverses. Can manage all Analytics links. "
                "Can manage all datasets. This user can access the web "
                "console but cannot read data.">>}],
      [{[analytics], [manage]},
       {[{bucket, any}, analytics], [manage]},
       {[ui], [read]},
       {[pools], [read]}]},
     {mobile_sync_gateway, [bucket_name],
      [{name, <<"Sync Gateway">>},
       {folder, mobile},
       {desc, <<"Full access to bucket data as required by Sync Gateway. "
                "This user cannot access the web console and is intended "
                "only for use by Sync Gateway. This user can read and "
                "write data, manage indexes and views, and read some "
                "cluster information.">>}],
      [{[{collection, [bucket_name, ?SYSTEM_SCOPE_NAME, "_mobile"]}, data],
        all},
       {[{bucket, bucket_name}, data, docs], [read, insert, delete, upsert,
                                              range_scan, sread]},
       {[{bucket, bucket_name}, data], all},
       {[{bucket, bucket_name}, views], all},
       {[{bucket, bucket_name}, n1ql, index], all},
       {[{bucket, bucket_name}, n1ql], [execute]},
       {[{bucket, bucket_name}], [read, flush]},
       {[{bucket, bucket_name}, settings], [read]},
       {[admin, memcached, idle], [write]},
       {[settings, autocompaction], [read]},
       {[pools], [read]}]},
     {sync_gateway_configurator, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Architect">>},
       {folder, mobile},
       {desc, <<"Can manage Sync Gateway databases and users, "
                "and access Sync Gateway's /metrics endpoint. "
                "This user cannot read application data.">>}],
      [{[{collection, [any, any, any]}, sgw, appdata], none},
       {[{collection, [any, any, any]}, sgw, principal_appdata], none},
       {[{collection, [any, any, any]}, sgw, replications], none},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw], all},
       {[admin, stats_export], [read]}]},
     {sync_gateway_app, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Application">>},
       {folder, mobile},
       {desc, <<"Can manage Sync Gateway users and roles, and "
                "read and write application data through Sync "
                "Gateway.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, auth], [configure]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal], [read, write]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, appdata], [read, write]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal_appdata],
        [read]}]},
     {sync_gateway_app_ro, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Application Read Only">>},
       {folder, mobile},
       {desc, <<"Can read Sync Gateway users and roles, and "
                "read application data through Sync Gateway.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, appdata], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal], [read]},
       {[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, principal_appdata],
        [read]}]},
     {sync_gateway_replicator, ?RBAC_COLLECTION_PARAMS,
      [{name, <<"Sync Gateway Replicator">>},
       {folder, mobile},
       {desc, <<"Can manage Inter-Sync Gateway Replications. "
                "This user cannot read application data.">>}],
      [{[{collection, ?RBAC_COLLECTION_PARAMS}, sgw, replications], all}]},
     {sync_gateway_dev_ops, [],
      [{name, <<"Sync Gateway Dev Ops">>},
       {folder, mobile},
       {desc, <<"Can manage Sync Gateway node-level configuration, "
                "and access Sync Gateway's /metrics endpoint "
                "for Prometheus integration.">>}],
      [{[sgw, dev_ops], all},
       {[admin, stats_export], [read]}]},
     {external_stats_reader, [],
      [{name, <<"External Stats Reader">>},
       {folder, admin},
       {desc, <<"Access to /metrics endpoint for Prometheus integration. "
                "Can read all stats for all services. This user cannot "
                "access the web console">>}],
      [{[admin, stats_export], [read]}]},
     {application_telemetry_writer, [],
      [{name, <<"Application Telemetry Writer">>},
       {folder, admin},
       {desc, <<"Can report application telemetry through the SDK. "
                "This user cannot access the web console">>}],
      [{[app_telemetry], [write]}]},
     {eventing_manage_functions, ?RBAC_SCOPE_PARAMS,
      [{name, <<"Manage Scope Functions">>},
       {folder, eventing},
       {desc, <<"Can manage eventing functions for a given scope">>}],
      [{[{collection, [bucket_name, scope_name, any]}, eventing, function],
        [manage]},
       {[{collection, [bucket_name, scope_name, any]}, collections], [read]},
       {[{bucket, bucket_name}, stats], [read]},
       {[ui], [read]},
       {[pools], [read]}]}
    ].

pre_totoro_ui_roles() ->
    [ro_admin, security_admin, ro_security_admin, user_admin_local,
     user_admin_external, cluster_admin, eventing_admin, backup_admin,
     bucket_admin, views_admin, replication_admin, fts_admin, fts_searcher,
     query_select, query_update, query_insert, query_delete, query_manage_index,
     query_list_index, query_system_catalog, query_external_access,
     query_manage_global_functions, query_execute_global_functions,
     query_manage_functions, query_execute_functions,
     query_manage_global_external_functions,
     query_execute_global_external_functions, query_manage_external_functions,
     query_execute_external_functions, query_manage_sequences,
     query_use_sequences, query_manage_system_catalog, analytics_manager,
     analytics_reader, analytics_select, analytics_admin,
     eventing_manage_functions].
