dist: xenial
sudo: false
language: go
go:
  - 1.12.x

env:
  - GO111MODULE=on

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

after_success:
  - bash <(curl -s https://codecov.io/bash)
