#!/bin/sh
#
# @author Couchbase <info@couchbase.com>
# @copyright 2018 Couchbase, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Pass-through the hook invocation to a hook from .git/hooks.old directory,
# that's created by git hooks --install and contains whatever hooks existed in
# the filesystem before. One example of such a hook would be a commit-msg hook
# that repo installs to add Change-Id to the commit message.

HOOKNAME=$(basename "$(dirname "$0")")
OLD_HOOK=".git/hooks.old/$HOOKNAME"

if test -x "$OLD_HOOK"; then
    "$OLD_HOOK" "$@"
fi
