#!/bin/sh
#
# @author Couchbase <info@couchbase.com>
# @copyright 2016-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.
#
# Average cpu utilization.
#
# Example usage:
#
# ./cpu --period day stats_archives.json | ./avg_cpu --regex 'beam.smp|memcached'
#

REGEX='.*'
ARGS=$(getopt -o r: -l regex: -n "$0" -- "$@")

if [ $? != 0 ]; then
    exit 1
fi

eval set -- "$ARGS"

while true; do
    case "$1" in
        -r|--regex) REGEX=$2; shift 2;;
        --) shift; break;;
    esac
done

jq --arg regex "$REGEX" '
def getProcName: capture("^(?<proc>[^/]+)/") | .proc;

def combineEntries:
  group_by(.key) |
  map(
    .[0].key as $key |
    (map(.value) | add) as $value |
    {key: $key, value: $value});

def processProcs:
  to_entries |
  map(.key = (.key | getProcName)) |
  map(select(.key | test($regex))) |
  combineEntries |
  from_entries;

length as $n |
map(
  {total_cpu: .total_cpu} + (.cpu | processProcs) |
  to_entries) |
flatten |
combineEntries |
map(.value = .value / $n) |
from_entries
' "$@"
