#!/bin/bash
#
# @author Couchbase <info@couchbase.com>
# @copyright 2018 Couchbase, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

TAG="$1"
COMMIT="$2"

DATE=$(git show -s --pretty=format:%cD "$COMMIT" 2>/dev/null)
if [ $? -ne 0 ]; then
    echo "Failed to get commit's '$COMMIT' date" >&2
    exit 1
fi

echo "Tagging '$COMMIT' with tag '$TAG'. Tag date: $DATE"

export GIT_COMMITTER_DATE="$DATE"
TAG_OUTPUT=$(git tag -a -m "tagging $TAG" "$TAG" "$COMMIT" 2>&1)

if [ $? -ne 0 ]; then
    echo "FAILED: $TAG_OUTPUT"
else
    echo "OK"
fi
